server:
  port: 8080   # Gateway runs on port 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**
        - id: chat-service
          uri: http://chat-service:8081
          predicates:
            - Path=/api/conversations/**
            - Path=/api/messages/**
            - Path=/api/users/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true